spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecloud_curd
    username: root
    password: 9787768711
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
